# Generated by Django 4.2.2 on 2023-06-25 11:05

import department.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото')),
                ('position', models.CharField(choices=[('DR', 'Director'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Должность')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Оклад')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='department.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_department', to='department.employee', validators=[department.models.validate_director]),
        ),
    ]
